Repository qreater/HelmInspect, pull requests merged in 2025-03, with the labels that each got.

#1 feat: initialized helm-inspect and library
  .gitignore
  .header-config.txt
  .pre-commit-config.yaml
  README.md
  __init__.py
  helm_inspect/__init__.py
  helm_inspect/cli.py
  helm_inspect/core.py
  helm_inspect/utils.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#3 feat(cli): added calibration model for precise drift detection
  helm_inspect/cli.py
  helm_inspect/core.py
  helm_inspect/utils.py
Labels: enhancement

#8 feat(core): drift computation and summary logging
  helm_inspect/cli.py
  helm_inspect/core.py
  helm_inspect/main.py
  helm_inspect/utils.py
  helm_inspect/utils/__init__.py
  helm_inspect/utils/calibration.py
  helm_inspect/utils/cli.py
  helm_inspect/utils/cluster.py
  helm_inspect/utils/drift_check.py
  helm_inspect/utils/logger.py
  pyproject.toml
Labels: enhancement

#10 feat(integration): implemented optional slack notifications
  helm_inspect/integrations/slack.py
  helm_inspect/main.py
  helm_inspect/utils/calibration.py
  helm_inspect/utils/cli.py
  helm_inspect/utils/constant.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#6 feat(docs): README Init
  README.md
  docs/assets/logo.webp
Labels: documentation

#12 feat: implemented responsive landing page for helm-inspect
  .github/workflows/sync-fork.yaml
  landing/.gitignore
  landing/.prettierrc
  landing/eslint.config.js
  landing/index.html
  landing/package-lock.json
  landing/package.json
  landing/public/logo.svg
  landing/src/app.tsx
  landing/src/assets/logo/helm_inspect.svg
  landing/src/assets/styles/index.css
  landing/src/components/commandbox/commandbox.styles.ts
  landing/src/components/commandbox/commandbox.tsx
  landing/src/components/ctabox/ctabox.styles.ts
  landing/src/components/ctabox/ctabox.tsx
  landing/src/components/index.styles.ts
  landing/src/components/layout/layout.styles.ts
  landing/src/components/layout/layout.tsx
  landing/src/components/navbar/navbar.styles.ts
  landing/src/components/navbar/navbar.tsx
  landing/src/components/scenariobox/scenariobox.tsx
  landing/src/containers/how/how.styles.ts
  landing/src/containers/how/how.tsx
  landing/src/containers/landing/landing.styles.ts
  landing/src/containers/landing/landing.tsx
  landing/src/containers/why/why.styles.ts
  landing/src/containers/why/why.tsx
  landing/src/main.tsx
  landing/src/vite-env.d.ts
  landing/tsconfig.app.json
  landing/tsconfig.json
  landing/tsconfig.node.json
  landing/vercel.json
  landing/vite.config.ts
  pyproject.toml
Labels: documentation, enhancement
